/* ============================================================
   countries-data.js
   World Countries, Continents & Currencies dataset.
   Used by region.js for the Settings > Region & Currency panel.
   ============================================================ */

const WORLD_REGIONS = [
  {
    continent: 'Africa',
    countries: [
      { name: 'Algeria',                 code: 'DZ', currency: 'Algerian Dinar',         currencyCode: 'DZD', symbol: 'دج'   },
      { name: 'Angola',                  code: 'AO', currency: 'Angolan Kwanza',          currencyCode: 'AOA', symbol: 'Kz'   },
      { name: 'Benin',                   code: 'BJ', currency: 'West African CFA Franc',  currencyCode: 'XOF', symbol: 'Fr'   },
      { name: 'Botswana',                code: 'BW', currency: 'Botswana Pula',           currencyCode: 'BWP', symbol: 'P'    },
      { name: 'Burkina Faso',            code: 'BF', currency: 'West African CFA Franc',  currencyCode: 'XOF', symbol: 'Fr'   },
      { name: 'Burundi',                 code: 'BI', currency: 'Burundian Franc',         currencyCode: 'BIF', symbol: 'Fr'   },
      { name: 'Cabo Verde',              code: 'CV', currency: 'Cape Verdean Escudo',     currencyCode: 'CVE', symbol: '$'    },
      { name: 'Cameroon',                code: 'CM', currency: 'Central African CFA',     currencyCode: 'XAF', symbol: 'Fr'   },
      { name: 'Central African Rep.',    code: 'CF', currency: 'Central African CFA',     currencyCode: 'XAF', symbol: 'Fr'   },
      { name: 'Chad',                    code: 'TD', currency: 'Central African CFA',     currencyCode: 'XAF', symbol: 'Fr'   },
      { name: 'Comoros',                 code: 'KM', currency: 'Comorian Franc',          currencyCode: 'KMF', symbol: 'Fr'   },
      { name: 'Congo (Brazzaville)',     code: 'CG', currency: 'Central African CFA',     currencyCode: 'XAF', symbol: 'Fr'   },
      { name: 'Congo (Kinshasa)',        code: 'CD', currency: 'Congolese Franc',         currencyCode: 'CDF', symbol: 'Fr'   },
      { name: "Côte d'Ivoire",           code: 'CI', currency: 'West African CFA Franc',  currencyCode: 'XOF', symbol: 'Fr'   },
      { name: 'Djibouti',               code: 'DJ', currency: 'Djiboutian Franc',        currencyCode: 'DJF', symbol: 'Fr'   },
      { name: 'Egypt',                   code: 'EG', currency: 'Egyptian Pound',          currencyCode: 'EGP', symbol: 'E£'   },
      { name: 'Equatorial Guinea',       code: 'GQ', currency: 'Central African CFA',     currencyCode: 'XAF', symbol: 'Fr'   },
      { name: 'Eritrea',                 code: 'ER', currency: 'Eritrean Nakfa',          currencyCode: 'ERN', symbol: 'Nfk'  },
      { name: 'Eswatini',               code: 'SZ', currency: 'Swazi Lilangeni',         currencyCode: 'SZL', symbol: 'L'    },
      { name: 'Ethiopia',               code: 'ET', currency: 'Ethiopian Birr',          currencyCode: 'ETB', symbol: 'Br'   },
      { name: 'Gabon',                  code: 'GA', currency: 'Central African CFA',     currencyCode: 'XAF', symbol: 'Fr'   },
      { name: 'Gambia',                 code: 'GM', currency: 'Gambian Dalasi',          currencyCode: 'GMD', symbol: 'D'    },
      { name: 'Ghana',                  code: 'GH', currency: 'Ghanaian Cedi',           currencyCode: 'GHS', symbol: '₵'    },
      { name: 'Guinea',                 code: 'GN', currency: 'Guinean Franc',           currencyCode: 'GNF', symbol: 'Fr'   },
      { name: 'Guinea-Bissau',          code: 'GW', currency: 'West African CFA Franc',  currencyCode: 'XOF', symbol: 'Fr'   },
      { name: 'Kenya',                  code: 'KE', currency: 'Kenyan Shilling',         currencyCode: 'KES', symbol: 'KSh'  },
      { name: 'Lesotho',               code: 'LS', currency: 'Lesotho Loti',            currencyCode: 'LSL', symbol: 'L'    },
      { name: 'Liberia',               code: 'LR', currency: 'Liberian Dollar',         currencyCode: 'LRD', symbol: '$'    },
      { name: 'Libya',                 code: 'LY', currency: 'Libyan Dinar',            currencyCode: 'LYD', symbol: 'LD'   },
      { name: 'Madagascar',            code: 'MG', currency: 'Malagasy Ariary',         currencyCode: 'MGA', symbol: 'Ar'   },
      { name: 'Malawi',               code: 'MW', currency: 'Malawian Kwacha',         currencyCode: 'MWK', symbol: 'MK'   },
      { name: 'Mali',                 code: 'ML', currency: 'West African CFA Franc',  currencyCode: 'XOF', symbol: 'Fr'   },
      { name: 'Mauritania',           code: 'MR', currency: 'Mauritanian Ouguiya',     currencyCode: 'MRU', symbol: 'UM'   },
      { name: 'Mauritius',            code: 'MU', currency: 'Mauritian Rupee',         currencyCode: 'MUR', symbol: '₨'    },
      { name: 'Morocco',              code: 'MA', currency: 'Moroccan Dirham',         currencyCode: 'MAD', symbol: 'MAD'  },
      { name: 'Mozambique',           code: 'MZ', currency: 'Mozambican Metical',      currencyCode: 'MZN', symbol: 'MT'   },
      { name: 'Namibia',              code: 'NA', currency: 'Namibian Dollar',         currencyCode: 'NAD', symbol: '$'    },
      { name: 'Niger',                code: 'NE', currency: 'West African CFA Franc',  currencyCode: 'XOF', symbol: 'Fr'   },
      { name: 'Nigeria',              code: 'NG', currency: 'Nigerian Naira',          currencyCode: 'NGN', symbol: '₦'    },
      { name: 'Rwanda',               code: 'RW', currency: 'Rwandan Franc',           currencyCode: 'RWF', symbol: 'Fr'   },
      { name: 'São Tomé & Príncipe',  code: 'ST', currency: 'São Tomé Dobra',          currencyCode: 'STN', symbol: 'Db'   },
      { name: 'Senegal',              code: 'SN', currency: 'West African CFA Franc',  currencyCode: 'XOF', symbol: 'Fr'   },
      { name: 'Seychelles',           code: 'SC', currency: 'Seychellois Rupee',       currencyCode: 'SCR', symbol: '₨'    },
      { name: 'Sierra Leone',         code: 'SL', currency: 'Sierra Leonean Leone',    currencyCode: 'SLL', symbol: 'Le'   },
      { name: 'Somalia',              code: 'SO', currency: 'Somali Shilling',         currencyCode: 'SOS', symbol: 'Sh'   },
      { name: 'South Africa',         code: 'ZA', currency: 'South African Rand',      currencyCode: 'ZAR', symbol: 'R'    },
      { name: 'South Sudan',          code: 'SS', currency: 'South Sudanese Pound',    currencyCode: 'SSP', symbol: '£'    },
      { name: 'Sudan',                code: 'SD', currency: 'Sudanese Pound',          currencyCode: 'SDG', symbol: '£'    },
      { name: 'Tanzania',             code: 'TZ', currency: 'Tanzanian Shilling',      currencyCode: 'TZS', symbol: 'Sh'   },
      { name: 'Togo',                 code: 'TG', currency: 'West African CFA Franc',  currencyCode: 'XOF', symbol: 'Fr'   },
      { name: 'Tunisia',              code: 'TN', currency: 'Tunisian Dinar',          currencyCode: 'TND', symbol: 'DT'   },
      { name: 'Uganda',               code: 'UG', currency: 'Ugandan Shilling',        currencyCode: 'UGX', symbol: 'Sh'   },
      { name: 'Zambia',               code: 'ZM', currency: 'Zambian Kwacha',          currencyCode: 'ZMW', symbol: 'ZK'   },
      { name: 'Zimbabwe',             code: 'ZW', currency: 'Zimbabwean Dollar',       currencyCode: 'ZWL', symbol: '$'    },
    ]
  },
  {
    continent: 'Asia',
    countries: [
      { name: 'Afghanistan',          code: 'AF', currency: 'Afghan Afghani',          currencyCode: 'AFN', symbol: '؋'    },
      { name: 'Armenia',              code: 'AM', currency: 'Armenian Dram',           currencyCode: 'AMD', symbol: '֏'    },
      { name: 'Azerbaijan',           code: 'AZ', currency: 'Azerbaijani Manat',       currencyCode: 'AZN', symbol: '₼'    },
      { name: 'Bahrain',              code: 'BH', currency: 'Bahraini Dinar',          currencyCode: 'BHD', symbol: '.د.ب' },
      { name: 'Bangladesh',           code: 'BD', currency: 'Bangladeshi Taka',        currencyCode: 'BDT', symbol: '৳'    },
      { name: 'Bhutan',               code: 'BT', currency: 'Bhutanese Ngultrum',      currencyCode: 'BTN', symbol: 'Nu'   },
      { name: 'Brunei',               code: 'BN', currency: 'Brunei Dollar',           currencyCode: 'BND', symbol: '$'    },
      { name: 'Cambodia',             code: 'KH', currency: 'Cambodian Riel',          currencyCode: 'KHR', symbol: '៛'    },
      { name: 'China',                code: 'CN', currency: 'Chinese Yuan',            currencyCode: 'CNY', symbol: '¥'    },
      { name: 'Cyprus',               code: 'CY', currency: 'Euro',                   currencyCode: 'EUR', symbol: '€'    },
      { name: 'Georgia',              code: 'GE', currency: 'Georgian Lari',           currencyCode: 'GEL', symbol: '₾'    },
      { name: 'India',                code: 'IN', currency: 'Indian Rupee',            currencyCode: 'INR', symbol: '₹'    },
      { name: 'Indonesia',            code: 'ID', currency: 'Indonesian Rupiah',       currencyCode: 'IDR', symbol: 'Rp'   },
      { name: 'Iran',                 code: 'IR', currency: 'Iranian Rial',            currencyCode: 'IRR', symbol: '﷼'    },
      { name: 'Iraq',                 code: 'IQ', currency: 'Iraqi Dinar',             currencyCode: 'IQD', symbol: 'ع.د'  },
      { name: 'Israel',               code: 'IL', currency: 'Israeli New Shekel',      currencyCode: 'ILS', symbol: '₪'    },
      { name: 'Japan',                code: 'JP', currency: 'Japanese Yen',            currencyCode: 'JPY', symbol: '¥'    },
      { name: 'Jordan',               code: 'JO', currency: 'Jordanian Dinar',         currencyCode: 'JOD', symbol: 'JD'   },
      { name: 'Kazakhstan',           code: 'KZ', currency: 'Kazakhstani Tenge',       currencyCode: 'KZT', symbol: '₸'    },
      { name: 'Kuwait',               code: 'KW', currency: 'Kuwaiti Dinar',           currencyCode: 'KWD', symbol: 'KD'   },
      { name: 'Kyrgyzstan',           code: 'KG', currency: 'Kyrgyzstani Som',         currencyCode: 'KGS', symbol: 'с'    },
      { name: 'Laos',                 code: 'LA', currency: 'Lao Kip',                 currencyCode: 'LAK', symbol: '₭'    },
      { name: 'Lebanon',              code: 'LB', currency: 'Lebanese Pound',          currencyCode: 'LBP', symbol: 'L£'   },
      { name: 'Malaysia',             code: 'MY', currency: 'Malaysian Ringgit',       currencyCode: 'MYR', symbol: 'RM'   },
      { name: 'Maldives',             code: 'MV', currency: 'Maldivian Rufiyaa',       currencyCode: 'MVR', symbol: 'Rf'   },
      { name: 'Mongolia',             code: 'MN', currency: 'Mongolian Tögrög',        currencyCode: 'MNT', symbol: '₮'    },
      { name: 'Myanmar',              code: 'MM', currency: 'Burmese Kyat',            currencyCode: 'MMK', symbol: 'K'    },
      { name: 'Nepal',                code: 'NP', currency: 'Nepalese Rupee',          currencyCode: 'NPR', symbol: '₨'    },
      { name: 'North Korea',          code: 'KP', currency: 'North Korean Won',        currencyCode: 'KPW', symbol: '₩'    },
      { name: 'Oman',                 code: 'OM', currency: 'Omani Rial',              currencyCode: 'OMR', symbol: 'ر.ع.' },
      { name: 'Pakistan',             code: 'PK', currency: 'Pakistani Rupee',         currencyCode: 'PKR', symbol: '₨'    },
      { name: 'Palestine',            code: 'PS', currency: 'Israeli New Shekel',      currencyCode: 'ILS', symbol: '₪'    },
      { name: 'Philippines',          code: 'PH', currency: 'Philippine Peso',         currencyCode: 'PHP', symbol: '₱'    },
      { name: 'Qatar',                code: 'QA', currency: 'Qatari Riyal',            currencyCode: 'QAR', symbol: 'QR'   },
      { name: 'Saudi Arabia',         code: 'SA', currency: 'Saudi Riyal',             currencyCode: 'SAR', symbol: 'SR'   },
      { name: 'Singapore',            code: 'SG', currency: 'Singapore Dollar',        currencyCode: 'SGD', symbol: '$'    },
      { name: 'South Korea',          code: 'KR', currency: 'South Korean Won',        currencyCode: 'KRW', symbol: '₩'    },
      { name: 'Sri Lanka',            code: 'LK', currency: 'Sri Lankan Rupee',        currencyCode: 'LKR', symbol: '₨'    },
      { name: 'Syria',                code: 'SY', currency: 'Syrian Pound',            currencyCode: 'SYP', symbol: '£'    },
      { name: 'Taiwan',               code: 'TW', currency: 'New Taiwan Dollar',       currencyCode: 'TWD', symbol: '$'    },
      { name: 'Tajikistan',           code: 'TJ', currency: 'Tajikistani Somoni',      currencyCode: 'TJS', symbol: 'SM'   },
      { name: 'Thailand',             code: 'TH', currency: 'Thai Baht',              currencyCode: 'THB', symbol: '฿'    },
      { name: 'Timor-Leste',          code: 'TL', currency: 'US Dollar',              currencyCode: 'USD', symbol: '$'    },
      { name: 'Turkey',               code: 'TR', currency: 'Turkish Lira',           currencyCode: 'TRY', symbol: '₺'    },
      { name: 'Turkmenistan',         code: 'TM', currency: 'Turkmenistan Manat',     currencyCode: 'TMT', symbol: 'T'    },
      { name: 'United Arab Emirates', code: 'AE', currency: 'UAE Dirham',             currencyCode: 'AED', symbol: 'د.إ'  },
      { name: 'Uzbekistan',           code: 'UZ', currency: 'Uzbekistani Som',         currencyCode: 'UZS', symbol: 'сўм'  },
      { name: 'Vietnam',              code: 'VN', currency: 'Vietnamese Đồng',         currencyCode: 'VND', symbol: '₫'    },
      { name: 'Yemen',                code: 'YE', currency: 'Yemeni Rial',             currencyCode: 'YER', symbol: '﷼'    },
    ]
  },
  {
    continent: 'Europe',
    countries: [
      { name: 'Albania',              code: 'AL', currency: 'Albanian Lek',            currencyCode: 'ALL', symbol: 'L'    },
      { name: 'Andorra',              code: 'AD', currency: 'Euro',                   currencyCode: 'EUR', symbol: '€'    },
      { name: 'Austria',              code: 'AT', currency: 'Euro',                   currencyCode: 'EUR', symbol: '€'    },
      { name: 'Belarus',              code: 'BY', currency: 'Belarusian Ruble',        currencyCode: 'BYN', symbol: 'Br'   },
      { name: 'Belgium',              code: 'BE', currency: 'Euro',                   currencyCode: 'EUR', symbol: '€'    },
      { name: 'Bosnia & Herzegovina', code: 'BA', currency: 'Bosnia Convertible Mark', currencyCode: 'BAM', symbol: 'KM'   },
      { name: 'Bulgaria',             code: 'BG', currency: 'Bulgarian Lev',          currencyCode: 'BGN', symbol: 'лв'   },
      { name: 'Croatia',              code: 'HR', currency: 'Euro',                   currencyCode: 'EUR', symbol: '€'    },
      { name: 'Czech Republic',       code: 'CZ', currency: 'Czech Koruna',           currencyCode: 'CZK', symbol: 'Kč'   },
      { name: 'Denmark',              code: 'DK', currency: 'Danish Krone',           currencyCode: 'DKK', symbol: 'kr'   },
      { name: 'Estonia',              code: 'EE', currency: 'Euro',                   currencyCode: 'EUR', symbol: '€'    },
      { name: 'Finland',              code: 'FI', currency: 'Euro',                   currencyCode: 'EUR', symbol: '€'    },
      { name: 'France',               code: 'FR', currency: 'Euro',                   currencyCode: 'EUR', symbol: '€'    },
      { name: 'Germany',              code: 'DE', currency: 'Euro',                   currencyCode: 'EUR', symbol: '€'    },
      { name: 'Greece',               code: 'GR', currency: 'Euro',                   currencyCode: 'EUR', symbol: '€'    },
      { name: 'Hungary',              code: 'HU', currency: 'Hungarian Forint',        currencyCode: 'HUF', symbol: 'Ft'   },
      { name: 'Iceland',              code: 'IS', currency: 'Icelandic Króna',         currencyCode: 'ISK', symbol: 'kr'   },
      { name: 'Ireland',              code: 'IE', currency: 'Euro',                   currencyCode: 'EUR', symbol: '€'    },
      { name: 'Italy',                code: 'IT', currency: 'Euro',                   currencyCode: 'EUR', symbol: '€'    },
      { name: 'Kosovo',               code: 'XK', currency: 'Euro',                   currencyCode: 'EUR', symbol: '€'    },
      { name: 'Latvia',               code: 'LV', currency: 'Euro',                   currencyCode: 'EUR', symbol: '€'    },
      { name: 'Liechtenstein',        code: 'LI', currency: 'Swiss Franc',            currencyCode: 'CHF', symbol: 'Fr'   },
      { name: 'Lithuania',            code: 'LT', currency: 'Euro',                   currencyCode: 'EUR', symbol: '€'    },
      { name: 'Luxembourg',           code: 'LU', currency: 'Euro',                   currencyCode: 'EUR', symbol: '€'    },
      { name: 'Malta',                code: 'MT', currency: 'Euro',                   currencyCode: 'EUR', symbol: '€'    },
      { name: 'Moldova',              code: 'MD', currency: 'Moldovan Leu',           currencyCode: 'MDL', symbol: 'L'    },
      { name: 'Monaco',               code: 'MC', currency: 'Euro',                   currencyCode: 'EUR', symbol: '€'    },
      { name: 'Montenegro',           code: 'ME', currency: 'Euro',                   currencyCode: 'EUR', symbol: '€'    },
      { name: 'Netherlands',          code: 'NL', currency: 'Euro',                   currencyCode: 'EUR', symbol: '€'    },
      { name: 'North Macedonia',      code: 'MK', currency: 'Macedonian Denar',       currencyCode: 'MKD', symbol: 'ден'  },
      { name: 'Norway',               code: 'NO', currency: 'Norwegian Krone',        currencyCode: 'NOK', symbol: 'kr'   },
      { name: 'Poland',               code: 'PL', currency: 'Polish Złoty',           currencyCode: 'PLN', symbol: 'zł'   },
      { name: 'Portugal',             code: 'PT', currency: 'Euro',                   currencyCode: 'EUR', symbol: '€'    },
      { name: 'Romania',              code: 'RO', currency: 'Romanian Leu',           currencyCode: 'RON', symbol: 'lei'  },
      { name: 'Russia',               code: 'RU', currency: 'Russian Ruble',          currencyCode: 'RUB', symbol: '₽'    },
      { name: 'San Marino',           code: 'SM', currency: 'Euro',                   currencyCode: 'EUR', symbol: '€'    },
      { name: 'Serbia',               code: 'RS', currency: 'Serbian Dinar',          currencyCode: 'RSD', symbol: 'din'  },
      { name: 'Slovakia',             code: 'SK', currency: 'Euro',                   currencyCode: 'EUR', symbol: '€'    },
      { name: 'Slovenia',             code: 'SI', currency: 'Euro',                   currencyCode: 'EUR', symbol: '€'    },
      { name: 'Spain',                code: 'ES', currency: 'Euro',                   currencyCode: 'EUR', symbol: '€'    },
      { name: 'Sweden',               code: 'SE', currency: 'Swedish Krona',          currencyCode: 'SEK', symbol: 'kr'   },
      { name: 'Switzerland',          code: 'CH', currency: 'Swiss Franc',            currencyCode: 'CHF', symbol: 'Fr'   },
      { name: 'Ukraine',              code: 'UA', currency: 'Ukrainian Hryvnia',       currencyCode: 'UAH', symbol: '₴'    },
      { name: 'United Kingdom',       code: 'GB', currency: 'British Pound',          currencyCode: 'GBP', symbol: '£'    },
      { name: 'Vatican City',         code: 'VA', currency: 'Euro',                   currencyCode: 'EUR', symbol: '€'    },
    ]
  },
  {
    continent: 'North America',
    countries: [
      { name: 'Antigua & Barbuda',    code: 'AG', currency: 'East Caribbean Dollar',  currencyCode: 'XCD', symbol: '$'    },
      { name: 'Bahamas',              code: 'BS', currency: 'Bahamian Dollar',         currencyCode: 'BSD', symbol: '$'    },
      { name: 'Barbados',             code: 'BB', currency: 'Barbadian Dollar',        currencyCode: 'BBD', symbol: '$'    },
      { name: 'Belize',               code: 'BZ', currency: 'Belize Dollar',          currencyCode: 'BZD', symbol: '$'    },
      { name: 'Canada',               code: 'CA', currency: 'Canadian Dollar',        currencyCode: 'CAD', symbol: 'CA$'  },
      { name: 'Costa Rica',           code: 'CR', currency: 'Costa Rican Colón',      currencyCode: 'CRC', symbol: '₡'    },
      { name: 'Cuba',                 code: 'CU', currency: 'Cuban Peso',             currencyCode: 'CUP', symbol: '$'    },
      { name: 'Dominica',             code: 'DM', currency: 'East Caribbean Dollar',  currencyCode: 'XCD', symbol: '$'    },
      { name: 'Dominican Republic',   code: 'DO', currency: 'Dominican Peso',         currencyCode: 'DOP', symbol: 'RD$'  },
      { name: 'El Salvador',          code: 'SV', currency: 'US Dollar',              currencyCode: 'USD', symbol: '$'    },
      { name: 'Grenada',              code: 'GD', currency: 'East Caribbean Dollar',  currencyCode: 'XCD', symbol: '$'    },
      { name: 'Guatemala',            code: 'GT', currency: 'Guatemalan Quetzal',     currencyCode: 'GTQ', symbol: 'Q'    },
      { name: 'Haiti',                code: 'HT', currency: 'Haitian Gourde',         currencyCode: 'HTG', symbol: 'G'    },
      { name: 'Honduras',             code: 'HN', currency: 'Honduran Lempira',       currencyCode: 'HNL', symbol: 'L'    },
      { name: 'Jamaica',              code: 'JM', currency: 'Jamaican Dollar',        currencyCode: 'JMD', symbol: '$'    },
      { name: 'Mexico',               code: 'MX', currency: 'Mexican Peso',           currencyCode: 'MXN', symbol: '$'    },
      { name: 'Nicaragua',            code: 'NI', currency: 'Nicaraguan Córdoba',     currencyCode: 'NIO', symbol: 'C$'   },
      { name: 'Panama',               code: 'PA', currency: 'Panamanian Balboa',      currencyCode: 'PAB', symbol: 'B/.' },
      { name: 'Saint Kitts & Nevis',  code: 'KN', currency: 'East Caribbean Dollar',  currencyCode: 'XCD', symbol: '$'    },
      { name: 'Saint Lucia',          code: 'LC', currency: 'East Caribbean Dollar',  currencyCode: 'XCD', symbol: '$'    },
      { name: 'Saint Vincent',        code: 'VC', currency: 'East Caribbean Dollar',  currencyCode: 'XCD', symbol: '$'    },
      { name: 'Trinidad & Tobago',    code: 'TT', currency: 'Trinidad Dollar',        currencyCode: 'TTD', symbol: '$'    },
      { name: 'United States',        code: 'US', currency: 'US Dollar',              currencyCode: 'USD', symbol: '$'    },
    ]
  },
  {
    continent: 'South America',
    countries: [
      { name: 'Argentina',            code: 'AR', currency: 'Argentine Peso',         currencyCode: 'ARS', symbol: '$'    },
      { name: 'Bolivia',              code: 'BO', currency: 'Bolivian Boliviano',      currencyCode: 'BOB', symbol: 'Bs.' },
      { name: 'Brazil',               code: 'BR', currency: 'Brazilian Real',         currencyCode: 'BRL', symbol: 'R$'   },
      { name: 'Chile',                code: 'CL', currency: 'Chilean Peso',           currencyCode: 'CLP', symbol: '$'    },
      { name: 'Colombia',             code: 'CO', currency: 'Colombian Peso',         currencyCode: 'COP', symbol: '$'    },
      { name: 'Ecuador',              code: 'EC', currency: 'US Dollar',              currencyCode: 'USD', symbol: '$'    },
      { name: 'Guyana',               code: 'GY', currency: 'Guyanese Dollar',        currencyCode: 'GYD', symbol: '$'    },
      { name: 'Paraguay',             code: 'PY', currency: 'Paraguayan Guaraní',     currencyCode: 'PYG', symbol: '₲'    },
      { name: 'Peru',                 code: 'PE', currency: 'Peruvian Sol',           currencyCode: 'PEN', symbol: 'S/'   },
      { name: 'Suriname',             code: 'SR', currency: 'Surinamese Dollar',      currencyCode: 'SRD', symbol: '$'    },
      { name: 'Uruguay',              code: 'UY', currency: 'Uruguayan Peso',         currencyCode: 'UYU', symbol: '$'    },
      { name: 'Venezuela',            code: 'VE', currency: 'Venezuelan Bolívar',     currencyCode: 'VES', symbol: 'Bs.S' },
    ]
  },
  {
    continent: 'Oceania',
    countries: [
      { name: 'Australia',            code: 'AU', currency: 'Australian Dollar',      currencyCode: 'AUD', symbol: '$'    },
      { name: 'Fiji',                 code: 'FJ', currency: 'Fijian Dollar',          currencyCode: 'FJD', symbol: '$'    },
      { name: 'Kiribati',             code: 'KI', currency: 'Australian Dollar',      currencyCode: 'AUD', symbol: '$'    },
      { name: 'Marshall Islands',     code: 'MH', currency: 'US Dollar',              currencyCode: 'USD', symbol: '$'    },
      { name: 'Micronesia',           code: 'FM', currency: 'US Dollar',              currencyCode: 'USD', symbol: '$'    },
      { name: 'Nauru',                code: 'NR', currency: 'Australian Dollar',      currencyCode: 'AUD', symbol: '$'    },
      { name: 'New Zealand',          code: 'NZ', currency: 'New Zealand Dollar',     currencyCode: 'NZD', symbol: '$'    },
      { name: 'Palau',                code: 'PW', currency: 'US Dollar',              currencyCode: 'USD', symbol: '$'    },
      { name: 'Papua New Guinea',     code: 'PG', currency: 'Papua New Guinean Kina', currencyCode: 'PGK', symbol: 'K'    },
      { name: 'Samoa',                code: 'WS', currency: 'Samoan Tālā',            currencyCode: 'WST', symbol: 'T'    },
      { name: 'Solomon Islands',      code: 'SB', currency: 'Solomon Islands Dollar', currencyCode: 'SBD', symbol: '$'    },
      { name: 'Tonga',                code: 'TO', currency: 'Tongan Paʻanga',         currencyCode: 'TOP', symbol: 'T$'   },
      { name: 'Tuvalu',               code: 'TV', currency: 'Australian Dollar',      currencyCode: 'AUD', symbol: '$'    },
      { name: 'Vanuatu',              code: 'VU', currency: 'Vanuatu Vatu',           currencyCode: 'VUV', symbol: 'Vt'   },
    ]
  },
];
